name: Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint autopep8 black flake8

      - name: Run auto-formatters
        run: |
          autopep8 --in-place --recursive .
          black .

      - name: Lint with pylint
        run: pylint $(git ls-files '*.py') || true  # Prevents build failure on warnings

      - name: Check for linting errors
        run: flake8 .
